version: "3.8"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: copy_of_wanago
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./copy-of-wanago.io-backend
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/copy_of_wanago"
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./copy-of-wanago.io-front
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data:
